// Auto-generated by scripts/gen-abis.mjs from <repo>/deployments/abis. Do not edit.

export { palissageLensAbi } from './PalissageLens';
export { wineLotTokenAbi } from './WineLotToken';
export { primaryMarketAbi } from './PrimaryMarket';
export { secondaryMarketAbi } from './SecondaryMarket';
export { redemptionManagerAbi } from './RedemptionManager';
export { identityRegistryAbi } from './IdentityRegistry';
export { trustedIssuersRegistryAbi } from './TrustedIssuersRegistry';
export { roleGatewayAbi } from './RoleGateway';
export { erc20Abi } from './Erc20';
