/**
 * Regenerates src/chain/abis/*.ts from the published deployment ABIs in
 * <repo>/deployments/abis. Those files are the ones the manifest points at, so
 * the interface and the verified sources cannot drift.
 *
 *   node scripts/gen-abis.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..');
const repo = join(web, '..', '..');
const source = join(repo, 'deployments', 'abis');
const dest = join(web, 'src', 'chain', 'abis');

const MAP = {
  palissageLens: 'PalissageLens',
  wineLotToken: 'WineLotToken',
  primaryMarket: 'PrimaryMarket',
  secondaryMarket: 'SecondaryMarket',
  redemptionManager: 'RedemptionManager',
  identityRegistry: 'IdentityRegistry',
  trustedIssuersRegistry: 'TrustedIssuersRegistry',
  roleGateway: 'RoleGateway',
};

mkdirSync(dest, { recursive: true });

const index = [
  '// Auto-generated by scripts/gen-abis.mjs from <repo>/deployments/abis. Do not edit.',
  '',
];

for (const [exportName, artifact] of Object.entries(MAP)) {
  const abi = JSON.parse(readFileSync(join(source, `${artifact}.json`), 'utf8'));
  const body = [
    `// Auto-generated from deployments/abis/${artifact}.json — do not edit by hand.`,
    `export const ${exportName}Abi = ${JSON.stringify(abi, null, 2)} as const;`,
    '',
  ].join('\n');
  writeFileSync(join(dest, `${artifact}.ts`), body);
  index.push(`export { ${exportName}Abi } from './${artifact}';`);
}

index.push("export { erc20Abi } from './Erc20';", '');
writeFileSync(join(dest, 'index.ts'), index.join('\n'));
console.log(`Wrote ${Object.keys(MAP).length} ABI modules to ${dest}`);
